// actions

export const FETCH_POST_LOGIN = 'FETCH_POST_LOGIN'

export const INIT_USRE_INFO_FROM_STORAGE = 'INIT_USRE_INFO_FROM_STORAGE'

// mutations

export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
